### ISSUE TITLE
macOS 新建项目失败

### ISSUE THREAD

**Issue by zuozijian3720** [bramblex/tauri_lite#6]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/17165520/226373500-6b8ace8d-c9c7-40ca-b0af-653dfbf52465.png">
打不开新建项目的窗口

**Comment by bramblex** [comment]
已在 #8 pr 里面修复

**Comment by bramblex** [comment]
https://github.com/bramblex/tauri_lite/releases/tag/v0.0.3
